In [30]:
# https://stackoverflow.com/questions/46700326/calculate-distances-between-one-point-in-matrix-from-all-other-points
# https://blog.csdn.net/qq_39028117/article/details/80033428

In [18]:
import numpy as np

In [13]:
x= np.arange(3)

In [14]:
x[np.newaxis,:] - x[:, np.newaxis]

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [15]:
(x[:, np.newaxis] - x[np.newaxis,:])**2

array([[0, 1, 4],
       [1, 0, 1],
       [4, 1, 0]], dtype=int32)

In [16]:
((x[:, np.newaxis] - x[np.newaxis,:])**2).sum(axis = -1)

array([5, 2, 5], dtype=int32)

In [17]:
((x[:, np.newaxis] - x[np.newaxis,:])**2).shape

(3, 3)

In [20]:
a = np.random.randint(0,10,(5,3))

In [21]:
a

array([[4, 1, 2],
       [9, 6, 5],
       [5, 3, 4],
       [2, 1, 8],
       [7, 1, 2]])

In [23]:
(a - a[:,None]).shape

(5, 5, 3)

In [24]:
a[:,None].shape

(5, 1, 3)

In [27]:
a[:,None]

array([[[4, 1, 2]],

       [[9, 6, 5]],

       [[5, 3, 4]],

       [[2, 1, 8]],

       [[7, 1, 2]]])

In [29]:
a.shape

(5, 3)

In [ ]:
a