In [1]:
import numpy as np
import pandas as pd

In [20]:
np.random.randint(5,7, size = 8 ) #[5, 7)

array([5, 6, 6, 6, 5, 6, 6, 5])

In [10]:
np.random.randint(5,7, size = (2,4))

array([[5, 6, 6, 6],
       [6, 5, 5, 5]])

In [21]:
x3 = np.random.randint(10, size=(3, 4, 5, 2)) 

In [25]:
x3.ndim, x3.shape, x3.size, x3.dtype

(4, (3, 4, 5, 2), 120, dtype('int64'))

In [31]:
x3[-1,-1,-1]

array([3, 9])

In [27]:
x3

array([[[[2, 0],
         [9, 1],
         [3, 8],
         [6, 1],
         [7, 2]],

        [[6, 4],
         [4, 4],
         [8, 9],
         [6, 9],
         [9, 0]],

        [[6, 2],
         [4, 1],
         [9, 4],
         [6, 9],
         [2, 9]],

        [[8, 3],
         [1, 7],
         [7, 7],
         [8, 5],
         [8, 3]]],


       [[[3, 6],
         [6, 6],
         [4, 4],
         [4, 4],
         [0, 3]],

        [[8, 8],
         [4, 0],
         [1, 8],
         [2, 4],
         [9, 4]],

        [[9, 5],
         [2, 8],
         [0, 6],
         [8, 6],
         [7, 6]],

        [[1, 8],
         [7, 1],
         [6, 1],
         [2, 4],
         [2, 0]]],


       [[[0, 4],
         [7, 4],
         [3, 2],
         [2, 8],
         [2, 8]],

        [[8, 8],
         [9, 6],
         [8, 6],
         [3, 8],
         [5, 1]],

        [[9, 7],
         [7, 6],
         [1, 8],
         [0, 6],
         [2, 6]],

        [[0, 7],
         [6, 0],
     

In [32]:
x = np.arange(10)

In [35]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x[:5]

array([0, 1, 2, 3, 4])

In [34]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
x[:5:-2]

array([9, 7])

In [39]:
x2 = np.random.randint(10, size=(3, 4))

In [40]:
x2

array([[9, 5, 9, 4],
       [7, 7, 6, 1],
       [4, 4, 5, 6]])

In [41]:
x2[:2,:3]

array([[9, 5, 9],
       [7, 7, 6]])

In [43]:
x2[::3,:3]

array([[9, 5, 9]])

In [45]:
np.random.randint(10,size=(2,3))

array([[4, 9, 8],
       [7, 6, 9]])

In [52]:
y = np.ones((2,4))

In [53]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
y = np.ones(3)

In [55]:
y

array([1., 1., 1.])

In [56]:
y.shape

(3,)

In [59]:
y[:,np.newaxis]

array([[1.],
       [1.],
       [1.]])

In [60]:
y[:,np.newaxis].shape

(3, 1)

In [61]:
y[np.newaxis,:].shape

(1, 3)

In [62]:
y[np.newaxis,:]

array([[1., 1., 1.]])

In [63]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
10//11

0

In [70]:
10%4

2

In [72]:
-10/3

-3.3333333333333335

In [74]:
-10%3

2

In [79]:
np.linspace(2,3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [80]:
np.exp(2)

7.38905609893065

In [82]:
np.exp2(4)

16.0

In [85]:
np.power(4,4)

256

In [86]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out =y)

array([ 0., 10., 20., 30., 40.])

In [91]:
np.power(2,x,out=y)

array([ 1.,  2.,  4.,  8., 16.])

In [93]:
y

array([ 1.,  2.,  4.,  8., 16.])

In [94]:
y.astype('int')

array([ 1,  2,  4,  8, 16])

In [95]:
np.add.reduce([2,4,6,1,7])

20

In [96]:
np.sum([2,4,6,1,7])

20

In [97]:
np.cumsum([2,4,6,1,7])

array([ 2,  6, 12, 13, 20])

In [99]:
np.add.reduce(np.arange(10))

45

In [100]:
np.add.accumulate(np.arange(10))

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [101]:
np.cumsum(np.arange(10))

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [104]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [105]:
np.multiply(np.arange(1,6), np.arange(1,6))

array([ 1,  4,  9, 16, 25])

In [106]:
np.multiply.outer(np.arange(1,6), np.arange(1,6))

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [3]:
"hello world".upper()

'HELLO WORLD'

In [5]:
s = "hello world"

In [8]:
s.split(" ")

['hello', 'world']

In [9]:
message = "hello world"
capitalized_message = " ".join([
   word.capitalize()
   for word in message.split(" ")
])
print(capitalized_message) # Hello World

Hello World


In [11]:
message.title()

'Hello World'

In [13]:
np.random.rand(10)

array([0.62205375, 0.28511145, 0.11038502, 0.63144234, 0.83023757,
       0.39782199, 0.72060903, 0.03927641, 0.15539734, 0.8874654 ])

In [16]:
np.random.randint(10, size =(2,5))

array([[8, 8, 4, 5, 0],
       [1, 0, 2, 8, 8]])

In [23]:
np.random.seed(0)
np.sum(np.random.randint(10, size = (2,5)),axis = 0)

array([14,  3,  8,  5, 11])

In [22]:
np.random.seed(0)
np.random.randint(10, size = (2,5))

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4]])

In [30]:
np.sum([1,2,3,np.nan])

nan

In [33]:
np.ones((1,3))

array([[1., 1., 1.]])

In [34]:
np.ones?